# ModelSim compile script for verification
# Generated by MyLogic ModelSim Integration

# Create work library if it doesn't exist
vlib work
vmap work work

# Compile Verilog files
vlog -work work test_simple_not_synthesis_verify_original.v test_simple_not_synthesis_verify_mapped.v test_simple_not_synthesis_verify_tb.v

# Run simulation
vsim -c -do "run -all; quit -f" test_simple_not_synthesis_verify_tb
# Ensure exit even if errors occur
quit -force
