# ModelSim compile script for verification
# Generated by MyLogic ModelSim Integration

# Create work library if it doesn't exist
vlib work
vmap work work

# Compile Verilog files
vlog -work work combinational_gates_optimization_verify_original.v combinational_gates_optimization_verify_mapped.v combinational_gates_optimization_verify_tb.v

# Run simulation
vsim -c -do "run -all; quit -f" combinational_gates_optimization_verify_tb
# Ensure exit even if errors occur
quit -force
